/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemeboxRouteImport } from './routes/memebox'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemixIdRouteImport } from './routes/remix.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeboxRoute = MemeboxRouteImport.update({
  id: '/memebox',
  path: '/memebox',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemixIdRoute = RemixIdRouteImport.update({
  id: '/remix/$id',
  path: '/remix/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/memebox': typeof MemeboxRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/remix/$id': typeof RemixIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/memebox': typeof MemeboxRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/remix/$id': typeof RemixIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/memebox': typeof MemeboxRoute
  '/profile': typeof ProfileRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/remix/$id': typeof RemixIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/memebox'
    | '/profile'
    | '/subscribe'
    | '/wallet'
    | '/remix/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/explore'
    | '/memebox'
    | '/profile'
    | '/subscribe'
    | '/wallet'
    | '/remix/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/explore'
    | '/memebox'
    | '/profile'
    | '/subscribe'
    | '/wallet'
    | '/remix/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  MemeboxRoute: typeof MemeboxRoute
  ProfileRoute: typeof ProfileRoute
  SubscribeRoute: typeof SubscribeRoute
  WalletRoute: typeof WalletRoute
  RemixIdRoute: typeof RemixIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memebox': {
      id: '/memebox'
      path: '/memebox'
      fullPath: '/memebox'
      preLoaderRoute: typeof MemeboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remix/$id': {
      id: '/remix/$id'
      path: '/remix/$id'
      fullPath: '/remix/$id'
      preLoaderRoute: typeof RemixIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  MemeboxRoute: MemeboxRoute,
  ProfileRoute: ProfileRoute,
  SubscribeRoute: SubscribeRoute,
  WalletRoute: WalletRoute,
  RemixIdRoute: RemixIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
